### PR TITLE
Add sourceFile option to parser compile()

### PR DESCRIPTION
**Pull request by pfrazee**
Hiya! I'm happy maintaining a fork, but if you're interested in this contrib, here's the PR.

Adds a `sourceFile` option to the parser's `compile()` method so that you can add generated types to an existing ts-morph project file.

### CODE REVIEW

**Comment by ggoodman** [comment]
Holy cow, I don't think I ever noticed this. @pfrazee are you still interested in pursuing this change? Sorry for the year-long ghosting 😞.

**Comment by pfrazee** [comment]
Oh nah, I moved on from the project. Don't feel any guilt at all -- all FOSS interactions are gifts!

If this is useful to you, keep it. Otherwise you can close.

**Comment by ggoodman** [comment]
@pfrazee I'm curious where you landed. At the time I built this, there weren't any other solutions that worked with collections of interrelated (`$ref`'d) schemas. Maybe the landscape has changed and there are less organic, free-range solutions I should know about :).

**Comment by pfrazee** [comment]
Unfortunately I don't recall, tbh!

**Pull request closed without merging**
